In [1]:
#Loading in Data

import pandas as pd

df = pd.read_csv("../data/PRE_PCA.csv")

df.head()

,match_id,game_length,puuid,gold_left,last_round,players_eliminated,time_eliminated,total_damage_to_players,placement
0,NA1_5214474372,2240.723633,VKwva7riXrRpNn_pQCF7Gx63CYKG4PxcbND2JnL3Tcceb6...,40,28,1,1676.477051,61,5
1,NA1_5214474372,2240.723633,CSZABWFZly3iWPGGobYZhYk9knB5J0-pUQbO02Zx85ShQv...,0,21,0,1216.563843,15,8
2,NA1_5214474372,2240.723633,B_mWPVRiuzGR-eUTN6CDIwkjbf_PXOmitrSgK3r-Yo38gK...,4,27,0,1608.733765,47,6
3,NA1_5214474372,2240.723633,_W30FKv18DHc61O6J_7rVUV5nrp779aWIE3MSuA0YS9Mcu...,0,33,1,1934.663574,94,4
4,NA1_5214474372,2240.723633,-rQ5Ep_GYZG2QjV9oB3GnGS494CbFg7oZWjGYLBKMW9efl...,1,26,0,1548.258301,46,7

In [2]:
#Dropping Qualitative Columns and Labels
df_new = df.drop(['match_id', 'puuid', 'placement'], axis=1)

df_new.head()

,game_length,gold_left,last_round,players_eliminated,time_eliminated,total_damage_to_players
0,2240.723633,40,28,1,1676.477051,61
1,2240.723633,0,21,0,1216.563843,15
2,2240.723633,4,27,0,1608.733765,47
3,2240.723633,0,33,1,1934.663574,94
4,2240.723633,1,26,0,1548.258301,46

In [3]:
#Normalization
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

df_scaled_array = scaler.fit_transform(df_new)

df_scaled = pd.DataFrame(df_scaled_array, columns=df_new.columns)

df_scaled.head()

,game_length,gold_left,last_round,players_eliminated,time_eliminated,total_damage_to_players
0,0.701756,2.308218,-0.884969,0.173684,-0.719364,-0.813224
1,0.701756,-0.542417,-2.437015,-0.736637,-2.534173,-1.767466
2,0.701756,-0.257353,-1.106690,-0.736637,-0.986677,-1.103646
3,0.701756,-0.542417,0.223634,0.173684,0.299436,-0.128659
4,0.701756,-0.471151,-1.328411,-0.736637,-1.225313,-1.124390

In [5]:
#Output to CSV
df_scaled.to_csv("../data/scaled_clustering_data.csv", index=False)

In [ ]:
|