In [2]:
import pandas as pd

#Loading in data and finding all trait names
df = pd.read_csv('../data/Q2_TRAITS_V_PLACEMENT.csv')

unique_trait_names = df['trait_name'].unique().tolist()

unique_trait_names

['TFT13_Ambusher',
 'TFT13_Bruiser',
 'TFT13_Challenger',
 'TFT13_Hoverboard',
 'TFT13_JunkerKing',
 'TFT13_Pugilist',
 'TFT13_Scrap',
 'TFT13_Sniper',
 'TFT13_Squad',
 'TFT13_Teamup_Reunion',
 'TFT13_Titan',
 'TFT13_Cabal',
 'TFT13_Experiment',
 'TFT13_Family',
 'TFT13_FormSwapper',
 'TFT13_Infused',
 'TFT13_Martialist',
 'TFT13_Warband',
 'TFT13_Academy',
 'TFT13_Ambassador',
 'TFT13_Invoker',
 'TFT13_Rebel',
 'TFT13_Sorcerer',
 'TFT13_Watcher',
 'TFT13_BloodHunter',
 'TFT13_Teamup_Mentorship',
 'TFT13_Hextech',
 'TFT13_MachineHerald',
 'TFT13_MissMageTrait',
 'TFT13_Crime',
 'TFT13_HighRoller',
 'TFT13_Teamup_Menaces',
 'TFT13_Teamup_UnlikelyDuo',
 'TFT13_Teamup_BloodBrothers',
 'TFT13_Teamup_Betrayal',
 'TFT13_Teamup_Sisters',
 'TFT13_Teamup_Geniuses']

In [3]:
#Code to get trait counts
pivot_df = df.pivot_table(
    index=['match_id', 'puuid', 'placement'],  
    columns='trait_name',                      
    values='num_units',                        
    aggfunc='sum',                             
    fill_value=0                               
).reset_index()

pivot_df['top_four'] = (pivot_df['placement'] < 5).astype(int)


pivot_df.drop(columns='placement', inplace=True)


cols = list(pivot_df.columns)

match_puuid = ['match_id', 'puuid']

all_traits = [c for c in cols if c not in (match_puuid + ['top_four'])]
final_cols = match_puuid + all_traits + ['top_four']
pivot_df = pivot_df[final_cols]


pivot_df.to_csv('../data/trait_counts.csv', index=False)

pivot_df.head()

trait_name,match_id,puuid,TFT13_Academy,TFT13_Ambassador,TFT13_Ambusher,TFT13_BloodHunter,TFT13_Bruiser,TFT13_Cabal,TFT13_Challenger,TFT13_Crime,...,TFT13_Teamup_Geniuses,TFT13_Teamup_Menaces,TFT13_Teamup_Mentorship,TFT13_Teamup_Reunion,TFT13_Teamup_Sisters,TFT13_Teamup_UnlikelyDuo,TFT13_Titan,TFT13_Warband,TFT13_Watcher,top_four
0,NA1_5207953898,1x8SiuU29wBehu4HwldU0tiLaoeYZKkyJatYg12fu8a56P...,0,0,2,0,1,0,1,0,...,0,0,0,2,0,0,2,0,0,1
1,NA1_5207953898,23nlj-mOFFeTPgkfSkE7oM0vXUkDvtCrUT9qt-NwnnhWav...,0,1,0,0,1,1,1,1,...,0,0,0,0,0,0,0,1,0,0
2,NA1_5207953898,43332cvV4A2mqb2W0JfRmsfY9djf-VGUgRyPY4wB0BLbtw...,3,0,0,0,0,0,0,0,...,0,0,0,0,0,0,4,1,0,0
3,NA1_5207953898,7iIW7cDfdPzm9o3z0uea93AooftwLNn9OHAvQ79gKJOUHG...,3,1,0,0,2,1,2,0,...,0,0,0,0,0,0,2,2,0,1
4,NA1_5207953898,FCVNYmfyGJb7c4xAU_CDzVjrFzXapffhOPPn6lXfE8Cmtt...,3,1,0,0,0,0,0,1,...,0,0,0,0,0,0,6,1,0,1

In [4]:
#Cleaning trait count data by dropping columns
trait_counts_df = pd.read_csv('../data/trait_counts.csv')


columns_to_drop = [
    'match_id',
    'puuid',
    'TFT13_Teamup_Betrayal',
    'TFT13_Teamup_BloodBrothers',
    'TFT13_Teamup_Geniuses',
    'TFT13_Teamup_Menaces',
    'TFT13_Teamup_Mentorship',
    'TFT13_Teamup_Reunion',
    'TFT13_Teamup_Sisters',
    'TFT13_Teamup_UnlikelyDuo'
]

trait_counts_cleaned = trait_counts_df.drop(columns=columns_to_drop, errors='ignore')

trait_counts_cleaned.to_csv('../data/trait_counts_cleaned.csv', index=False)

trait_counts_cleaned.head()

,TFT13_Academy,TFT13_Ambassador,TFT13_Ambusher,TFT13_BloodHunter,TFT13_Bruiser,TFT13_Cabal,TFT13_Challenger,TFT13_Crime,TFT13_Experiment,TFT13_Family,...,TFT13_Pugilist,TFT13_Rebel,TFT13_Scrap,TFT13_Sniper,TFT13_Sorcerer,TFT13_Squad,TFT13_Titan,TFT13_Warband,TFT13_Watcher,top_four
0,0,0,2,0,1,0,1,0,0,0,...,1,0,2,2,0,8,2,0,0,1
1,0,1,0,0,1,1,1,1,1,1,...,6,0,2,0,0,1,0,1,0,0
2,3,0,0,0,0,0,0,0,0,0,...,0,2,2,0,0,0,4,1,0,0
3,3,1,0,0,2,1,2,0,0,1,...,2,0,2,0,1,2,2,2,0,1
4,3,1,0,0,0,0,0,1,0,0,...,0,3,1,0,0,0,6,1,0,1

In [6]:
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

#Multinomial NB
df = pd.read_csv('../data/trait_counts_cleaned.csv')

X = df.drop(columns=['top_four'])
y = df['top_four']

X_train, X_test, y_train, y_test = train_test_split(
    X, 
    y, 
    test_size=0.2,   
    random_state=42  
)
feature_columns = df.drop(columns = ['top_four']).columns.tolist()

multinb_training_data = pd.DataFrame(X_train, columns = feature_columns)
multinb_training_data.to_csv("../data/multinb_training_data.csv", index=False)

multinb_testing_data = pd.DataFrame(X_test, columns = feature_columns)
multinb_testing_data.to_csv("../data/multinb_testing_data.csv", index=False)

In [7]:
model = MultinomialNB()
model.fit(X_train, y_train)


y_pred = model.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)
conf_mat = confusion_matrix(y_test, y_pred)
class_rep = classification_report(y_test, y_pred)

print("Accuracy:", accuracy)
print("Confusion Matrix:\n", conf_mat)
print("Classification Report:\n", class_rep)

Accuracy: 0.6244196843082637
Confusion Matrix:
 [[796 308]
 [501 549]]
Classification Report:
               precision    recall  f1-score   support

           0       0.61      0.72      0.66      1104
           1       0.64      0.52      0.58      1050

    accuracy                           0.62      2154
   macro avg       0.63      0.62      0.62      2154
weighted avg       0.63      0.62      0.62      2154