In [9]:
#Loading in Data

import pandas as pd

df = pd.read_csv("../data/PRE_PCA.csv")

df.head()

,match_id,game_length,puuid,gold_left,last_round,players_eliminated,time_eliminated,total_damage_to_players,placement
0,NA1_5214474372,2240.723633,VKwva7riXrRpNn_pQCF7Gx63CYKG4PxcbND2JnL3Tcceb6...,40,28,1,1676.477051,61,5
1,NA1_5214474372,2240.723633,CSZABWFZly3iWPGGobYZhYk9knB5J0-pUQbO02Zx85ShQv...,0,21,0,1216.563843,15,8
2,NA1_5214474372,2240.723633,B_mWPVRiuzGR-eUTN6CDIwkjbf_PXOmitrSgK3r-Yo38gK...,4,27,0,1608.733765,47,6
3,NA1_5214474372,2240.723633,_W30FKv18DHc61O6J_7rVUV5nrp779aWIE3MSuA0YS9Mcu...,0,33,1,1934.663574,94,4
4,NA1_5214474372,2240.723633,-rQ5Ep_GYZG2QjV9oB3GnGS494CbFg7oZWjGYLBKMW9efl...,1,26,0,1548.258301,46,7

In [ ]:
#Dropping Qualitative Columns and Labels
df_new = df.drop(['match_id', 'puuid', 'placement'], axis=1)

df_new.head()

,game_length,gold_left,last_round,players_eliminated,time_eliminated,total_damage_to_players
0,2240.723633,40,28,1,1676.477051,61
1,2240.723633,0,21,0,1216.563843,15
2,2240.723633,4,27,0,1608.733765,47
3,2240.723633,0,33,1,1934.663574,94
4,2240.723633,1,26,0,1548.258301,46

In [12]:
#Output to CSV
df_new.to_csv("../data/PCA.csv", index=False)